[[pingbeat-getting-started]]
== Getting started

[[pingbeat-configuration]]
=== Pingbeat configuration

Before starting Pingbeat, you'll need to edit the `pingbeat.yml`
configuration file and add your targets and change any configuration
options as described below.

[source, yaml]
-------------------------------------
input:
  period: 10
  privileged: true
  useipv4: true
  useipv6: false
  targets:
    - name: "127.0.0.1"
      tags: "localhost"
      desc: "there's no place like home"
-------------------------------------

`period` defines how often to send ping packets to all targets.

`privileged` defines whether to use ICMP (raw socket) packets (`true`)
or UDP packets (`false`). With `privileged: true`, Pingbeat will
require root/superuser privileges as only a user with these
permissions can open raw sockets.

`useipv4/useipv6` defines whether to send IPv4/v6 pings.  Toggle these
depending on your network configuration.

The target list is defined in a hierarchy under the
`targets` key. Hosts are defined by a `name` (required, either a
hostname or IP address), a list of tags and a description, the latter
two being optional.

Before starting Pingbeat, you need to load the
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/indices-templates.html[index
template], which is used to let Elasticsearch know which fields should be analyzed
in which way.

The recommended template file is available with the Pingbeat source. Load it with the
following command:

[source,shell]
----------------------------------------------------------------------
curl -XPUT 'http://localhost:9200/_template/pingbeat' -d@/path/to/pingbeat.template.json
----------------------------------------------------------------------

// The recommended template file is installed by the Pingbeat packages. Load it with the
// following command:

// deb or rpm:

// [source,shell]
// ----------------------------------------------------------------------
// curl -XPUT 'http://localhost:9200/_template/pingbeat' -d@/etc/pingbeat/pingbeat.template.json
// ----------------------------------------------------------------------

// mac:

// [source,shell]
// ----------------------------------------------------------------------
// cd pingbeat-$PB_VERSION-darwin
// curl -XPUT 'http://localhost:9200/_template/pingbeat' -d@pingbeat.template.json
// ----------------------------------------------------------------------

// where `localhost:9200` is the IP and port where Elasticsearch is listening on.

You are now ready to start Pingbeat:

[source,shell]
----------------------------------------------------------------------
sudo ./pingbeat -e -c /path/to/pingbeat.yml -d "publish"
----------------------------------------------------------------------

[[pingbeat-privileges]]
=== Pingbeat Privileges

In order to send regular ICMP ping packets, pingbeat needs to open raw
sockets, which can only be done with superuser privileges.  So you
either need to run pingbeat with sudo or as root to send regular
pings. If you don't want to do that, set `privileged: false` in your
config and run pingbeat as a regular user.  It will then use a `UDP
ping` to test connectivity.  You may still need to adjust the
`net.ipv4.ping_group_range` sysctl variable to allow a regular user to
send UDP ping packets.

Alternatively, on Linux you can grant pingbeat access to raw sockets
without the need to run with sudo or as root user, by granting the
binary `CAP_NET_RAW ` capability (see:  [capabilities](http://linux.die.net/man/7/capabilities);
for overview of Linux capabilities). To set necessary capability,
ensure that the `getcap` and `setcap` binaries are present (you
might need to install relevant packages from you distribution) in
your `PATH`, then execute the following: `setcap cap_net_raw+ep <PATH>`
where `PATH` is the location where the pingbeat binary was installed;
to verify execute the following: `getcap <PATH>`. Given that everything
went well, the output from `getcap` should indicate that pingbeat has
now `cap_net_raw+ep` capabilities set.
